

spring.application.name: api

spring.profiles.active: local

spring:
  config:
    import:
      - db.yml
      - jwt.yml
      - fcm.yml
      - ncp.yml
      - media.yml
      - openai.yml
      - optional:file:../.env[.properties]
      - optional:file:./.env[.properties]
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.chewing: DEBUG
    org.springframework.messaging: DEBUG
    org.apache.catalina: DEBUG

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 8080


#---
#spring.profiles.active: test
#
#---
#spring.profiles.active: live
